language: c

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - sudo pip install cpp-coveralls
  - sudo luarocks install lunitx --server=https://rocks.moonscript.org/manifests/moteus

install:
  - sudo luarocks make rockspecs/aesfileencrypt-scm-0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

script: 
  - cd test
  - lunit.sh -i lua$LUA_SFX test.lua

after_success:
  - coveralls -b .. -r .. -i src

notifications:
  email:
    on_success: change
    on_failure: always
